# The following properties are required for hawk (productive) deployment.
# For productive deployment, all properties must be configured or enabled.
# Only relevant properties should be listed here; otherwise, they should be deleted.
# Unless otherwise specified, empty properties are relevant and must be configured.
# Temporary disabled properties require further configuration or other dependencies.

##############################################################################
# Basic                                                                      #
##############################################################################
# Configure base url, e.g. http://domain:port, without '/'. Temporary disabled to use default.
#MCR.baseurl=
# Requires MCR.baseurl, therefore temporary disabled.
#MIR.CanonicalBaseURL=%MCR.baseurl%/
MCR.NameOfProject=noa
MIR.projectid.default=noa
MIR.testEnvironment=false
MCR.Metadata.Languages=de

##############################################################################
# Email                                                                      #
##############################################################################
MCR.Mail.Server=
# General sender mail address, e.g. mail@domain
MCR.Mail.Sender=
# Editor mail adresses for messages, e.g. mail@domain0,amail@domain1,..n.
MCR.Mail.Address=

# Sender email for events, e.g. <name> mail@domain
MCR.mir-module.MailSender=
# Mail for events including self registration, e.g. <name> mail@domain
MCR.mir-module.EditorMail=

##############################################################################
# Access Control                                                             #
##############################################################################
# Access keys are not relevant and must therefore be deactivated as follows.
MCR.ACL.AccessKey.Strategy.AllowedObjectTypes=
MIR.Access.Strategy.Classifications=mir_access,state

##############################################################################
# URN configuration                                                          #
##############################################################################
MCR.PI.MetadataService.MODSURN.Prefix=urn:nbn:de:gbv:35
MCR.PI.Generator.TypeYearCountURN.GeneralPattern=urn:nbn:de:gbv:35-$ObjectDate-$Count
MCR.PI.Generator.TypeYearCountURN.DateFormat=yyyyMMdd-HHmmss
MCR.PI.Generator.TypeYearCountURN.CountPrecision=1

##############################################################################
# OAI Data Provider                                                          #
##############################################################################
MCR.OAIDataProvider.OAI2.RepositoryName=NOA
MCR.OAIDataProvider.OAI2.RepositoryIdentifier=noa.gwlb.de
MCR.OAIDataProvider.OAI2.AdminEmail=
MCR.OAIDataProvider.OAI2.DescriptionURI.EPrints=webapp:oai/oai-eprints.xml
MCR.OAIDataProvider.OAI2.DescriptionURI.Rights=webapp:oai/oai-rights.xml
MCR.OAIDataProvider.OAI2.RecordSampleID=mir_mods_00000479
MCR.OAIDataProvider.OAI2.MetadataFormats=oai_dc,mods,epicur,xMetaDissPlus
MCR.OAIDataProvider.OAI2.Sets=doc-type,open_access,xmetadissplus,driver,GENRE,ddc,epicur

# Add epicur Set
MCR.OAIDataProvider.OAI2.Sets.epicur.URI=webapp:oai/set_epicur.xml
MCR.OAIDataProvider.OAI2.Sets.epicur.Query=mods.identifier:urn*

# Add xMetaDissPlus
MCR.OAIDataProvider.OAI2.Sets.xmetadissplus.Query=category.top:"noa_pubtype\:amtsdruckschrift" AND derCount:[1 TO *]
MCR.OAIDataProvider.OAI2.Sets.xmetadissplus.URI=webapp:oai/set_xmetadissplus.xml

# Set name, place and the address of the repository owner.
MCR.OAIDataProvider.RepositoryPublisherName=Gottfried Wilhelm Leibniz Bibliothek
MCR.OAIDataProvider.RepositoryPublisherPlace=Hannover
MCR.OAIDataProvider.RepositoryPublisherAddress=Waterloostr. 8, 30169 Hannover

# Define friendly OAI interfaces
MCR.OAIDataProvider.OAI2.Friends.OpenAgrar=https://www.openagrar.de/servlets/OAIDataProvider
MCR.OAIDataProvider.OAI2.Friends.DuEPublico=https://duepublico.uni-duisburg-essen.de/servlets/OAIDataProvider
MCR.OAIDataProvider.OAI2.Friends.DBThueringen=https://www.db-thueringen.de/servlets/OAIDataProvider
MCR.OAIDataProvider.OAI2.Friends.RosDok=https://rosdok.uni-rostock.de/oai

# Switch to DINI2022 conformity
MCR.OAIDataProvider.OAI2.Sets.doc-type.URI=xslStyle:classification2sets:classification:metadata:2:children:diniPublType2022
MCR.OAIDataProvider.OAI2.Sets.doc-type.Classification=diniPublType2022

# add ids of hosted periodicals
MIR.HostedPeriodicals.List=mir_mods_00000219,mir_mods_00000221,mir_mods_00000259,mir_mods_00000322,mir_mods_00000331,mir_mods_00000351,mir_mods_00000353,mir_mods_00000357,mir_mods_00000364,mir_mods_00000369,mir_mods_00000381,mir_mods_00000386,mir_mods_00000602,mir_mods_00000678,mir_mods_00000692,mir_mods_00000957,mir_mods_00000976,mir_mods_00000994,mir_mods_00001194,mir_mods_00001236,mir_mods_00001273,mir_mods_00001328,mir_mods_00001378,mir_mods_00001440,mir_mods_00001442,mir_mods_00001444,mir_mods_00001536,mir_mods_00001554,mir_mods_00001562,mir_mods_00001573,mir_mods_00001601,mir_mods_00001609,mir_mods_00001766,noa_mods_00000260,noa_mods_00000296,noa_mods_00000335,noa_mods_00000438,noa_mods_00000606,noa_mods_00000618,noa_mods_00000820,noa_mods_00000884,noa_mods_00000889,noa_mods_00001050,noa_mods_00001110,noa_mods_00001129,noa_mods_00001195,noa_mods_00001331,noa_mods_00001343,noa_mods_00001544,noa_mods_00001574,noa_mods_00001578,noa_mods_00001598,noa_mods_00001601,noa_mods_00002044,noa_mods_00002065,noa_mods_00002083,noa_mods_00002089,noa_mods_00002140,noa_mods_00002142,noa_mods_00002143,noa_mods_00002332,noa_mods_00002384,noa_mods_00002699,noa_mods_00002702,noa_mods_00003501,noa_mods_00003529,noa_mods_00003692


##############################################################################
# PPN Configuration                                                          #
##############################################################################
MIR.PPN.DatabaseList=opac-de-35

##############################################################################
# Enrichment                                                                 #
##############################################################################
# Mail for unpaywall requests, e.g. mail@domain
MIR.OADOI.Mail.Address=

##############################################################################
# Editor                                                                     #
##############################################################################
MIR.EditorForms.CustomIncludes=xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed
MCR.UserForms.CustomIncludes=authorization/custom-user-includes.xed

##############################################################################
# Frontend                                                                   #
##############################################################################
MCR.ContentTransformer.mcr_error.Stylesheet=xsl/errorPage.xsl,%MCR.LayoutTransformerFactory.Default.Stylesheets%
MIR.CustomLayout.JS=noa.js
MCR.ContentTransformer.response-filter.Class=org.mycore.common.content.transformer.MCRXSLTransformer
MCR.ContentTransformer.response-filter.Stylesheet=%MCR.ContentTransformer.response-prepared.Stylesheet%,xsl/response-filter.xsl,%MCR.LayoutTransformerFactory.Default.Stylesheets%
MIR.Response.Facet.noa.pubtype.ClassId=noa_pubtype

##############################################################################
# Solr                                                                       #
##############################################################################
MCR.URIResolver.xslImports.solr-document=%MCR.URIResolver.xslImports.solr-document%,noa-solr.xsl

##############################################################################
# MIR ePuSta                                                                    #
##############################################################################
# show ePuSta statistics in metadata view ('show', 'hide')
MIR.ePuSta=show
# URL of the ePuStaServer
MIR.ePuSta.providerURL=https://esx-141.gbv.de/noa/rest-api